import type { Metadata } from "next";
import "./globals.css";
import { Archivo } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { ToastProvider } from "@/components/Toast";

const archivo = Archivo({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} antialiased`}>
        <ToastProvider>
          <div className="flex h-screen">
            <Navbar />
            <Sidebar />
            <div className="flex-1 flex flex-col">
              <div className="flex-1 overflow-auto py-32 px-16 text-black">
                {children}
              </div>
            </div>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
